yml
language: python
python:
    - "3.8"
before_install:
    - pip install pytest pytest-cov
    - pip install codecov
script:
    - pytest --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)
